name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Jython (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          script/install_jython.sh
          echo ~/jython/bin >> $GITHUB_PATH
      - name: Install Jython (Windows)
        if: runner.os == 'Windows'
        run: |
          script\Install-Jython.ps1
          "$HOME\jython\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Install SWIG
        if: runner.os == 'macOS'
        run: brew install swig
      - name: Setup MSVC and C# Compiler
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          components: Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Microsoft.VisualStudio.Component.Roslyn.Compiler
      - name: Run test
        run: python -m unittest -v
